@extends('layouts.app')
@section('title','Chính sách mua hàng - Thành Đạt Taabusico')
@section('content')
<section class="page-hero policy-hero"><div class="container"><span class="eyebrow">Minh bạch và tận tâm</span><h1>Chính sách mua hàng</h1><p>Những thông tin cần thiết giúp bạn an tâm khi mua sắm tại Thành Đạt Taabusico.</p></div></section>
<section class="policy-layout container">
    <aside class="policy-nav"><b>Nội dung chính</b><a href="#mua-hang">Mua hàng</a><a href="#thanh-toan">Thanh toán</a><a href="#giao-nhan">Giao nhận</a><a href="#doi-tra">Đổi trả & hoàn tiền</a><a href="#bao-mat">Bảo mật thông tin</a><a href="#khieu-nai">Khiếu nại & hỗ trợ</a></aside>
    <div class="policy-content">
        <div class="policy-intro"><i class="fa-solid fa-shield-heart"></i><div><b>Cam kết của Thành Đạt</b><p>Chúng tôi tôn trọng quyền lợi khách hàng, cung cấp thông tin sản phẩm rõ ràng và hỗ trợ nhanh chóng trong suốt quá trình mua hàng.</p></div></div>
        <article id="mua-hang"><span>01</span><div><h2>Chính sách mua hàng</h2><p>Khách hàng có thể đặt mua trực tiếp trên website hoặc liên hệ hotline <b>0938.905.582</b>. Đơn hàng chỉ được xem là hợp lệ khi cung cấp đầy đủ họ tên, số điện thoại và địa chỉ nhận hàng.</p><ul><li>Giá bán được niêm yết bằng Việt Nam đồng và đã hiển thị rõ trên từng sản phẩm.</li><li>Thông tin tồn kho có thể thay đổi theo mùa vụ và thời điểm xác nhận đơn.</li><li>Cửa hàng có quyền liên hệ để xác minh thông tin trước khi giao hàng.</li></ul></div></article>
        <article id="thanh-toan"><span>02</span><div><h2>Chính sách thanh toán</h2><p>Thành Đạt hỗ trợ hai phương thức thanh toán để khách hàng thuận tiện lựa chọn:</p><ul><li><b>Thanh toán khi nhận hàng (COD):</b> thanh toán tiền mặt cho nhân viên giao hàng sau khi nhận sản phẩm.</li><li><b>Chuyển khoản PayOS:</b> thanh toán qua mã QR hoặc ứng dụng ngân hàng. Đơn được xác nhận thanh toán sau khi hệ thống nhận thông báo thành công.</li></ul><p>Khách hàng không chuyển tiền vào tài khoản không được công bố trên trang thanh toán chính thức của cửa hàng.</p></div></article>
        <article id="giao-nhan"><span>03</span><div><h2>Chính sách giao nhận</h2><p>Đơn hàng được xử lý theo thứ tự tiếp nhận và giao đến địa chỉ khách hàng cung cấp.</p><ul><li>Thời gian dự kiến trong nội thành: 1–2 ngày làm việc.</li><li>Các tỉnh thành khác: 2–5 ngày làm việc tùy khu vực.</li><li>Thời gian có thể thay đổi do thời tiết, mùa vụ, ngày lễ hoặc đơn vị vận chuyển.</li><li>Khách hàng vui lòng kiểm tra tình trạng bao bì và số lượng khi nhận hàng.</li></ul></div></article>
        <article id="doi-tra"><span>04</span><div><h2>Chính sách đổi trả và hoàn tiền</h2><p>Cửa hàng hỗ trợ đổi trả nếu sản phẩm giao sai, thiếu số lượng, hư hỏng do vận chuyển hoặc không đạt chất lượng tại thời điểm nhận.</p><ul><li>Thông báo trong vòng <b>24 giờ</b> kể từ khi nhận hàng.</li><li>Cung cấp mã đơn, hình ảnh sản phẩm và bao bì để cửa hàng kiểm tra.</li><li>Sản phẩm cần được giữ nguyên hiện trạng, chưa qua sử dụng hoặc chế biến.</li><li>Hoàn tiền được thực hiện qua phương thức phù hợp sau khi yêu cầu được chấp thuận.</li></ul><p>Không áp dụng đổi trả do thay đổi nhu cầu đối với sản phẩm tươi sống nếu sản phẩm được giao đúng và đảm bảo chất lượng.</p></div></article>
        <article id="bao-mat"><span>05</span><div><h2>Chính sách bảo mật thông tin</h2><p>Thông tin họ tên, số điện thoại, email và địa chỉ chỉ được sử dụng để xử lý đơn hàng, giao nhận, chăm sóc khách hàng và thực hiện nghĩa vụ pháp lý liên quan.</p><ul><li>Không bán hoặc trao đổi thông tin khách hàng cho bên thứ ba vì mục đích thương mại.</li><li>Chỉ chia sẻ thông tin cần thiết với đơn vị thanh toán và vận chuyển.</li><li>Khách hàng có thể yêu cầu kiểm tra, điều chỉnh hoặc xóa thông tin theo quy định pháp luật.</li></ul></div></article>
        <article id="khieu-nai"><span>06</span><div><h2>Khiếu nại và hỗ trợ</h2><p>Mọi phản hồi sẽ được tiếp nhận công bằng và xử lý trong thời gian sớm nhất.</p><div class="policy-contact"><a href="tel:0938905582"><i class="fa-solid fa-phone"></i><span><b>Hotline</b><small>0938.905.582</small></span></a><a href="mailto:congtytdfoods@gmail.com"><i class="fa-regular fa-envelope"></i><span><b>Email</b><small>congtytdfoods@gmail.com</small></span></a></div></div></article>
        <p class="policy-updated">Chính sách được cập nhật lần cuối ngày {{ now()->format('d/m/Y') }}. Thành Đạt có thể điều chỉnh nội dung để phù hợp với hoạt động kinh doanh và quy định pháp luật.</p>
    </div>
</section>
@endsection
