@extends('layouts.admin') @section('title','Cấu hình website') @section('content')
<div class="admin-title"><div><h1>Cấu hình website</h1><p>Quản lý SEO, email SMTP và nội dung menu.</p></div></div>
@if($errors->any())<div class="alert error">{{ $errors->first() }}</div>@endif
<form class="settings-form" method="post" action="{{ route('admin.settings.update') }}">@csrf @method('put')
<div class="settings-tabs"><button type="button" class="active" data-settings-tab="seo">SEO từng trang</button><button type="button" data-settings-tab="smtp">Cấu hình SMTP</button><button type="button" data-settings-tab="menu">Nội dung menu</button></div>
<section class="settings-pane active" data-settings-pane="seo">
    @php($favicon=$media->firstWhere('id',(int)old('favicon_image_id',$settings['site.favicon_image_id']??0)))
    <div class="panel"><div class="settings-section-head"><div><h2>Thông tin chung</h2><p>Tên thương hiệu và biểu tượng hiển thị trên tab trình duyệt.</p></div></div><div class="settings-grid"><label class="setting-field span-2">Tên website<input name="site_name" value="{{ old('site_name',$settings['site.name']??'Thành Đạt Taabusico') }}" required></label><div class="setting-field"><b>Favicon</b><input id="favicon-image-id" type="hidden" name="favicon_image_id" value="{{ old('favicon_image_id',$settings['site.favicon_image_id']??'') }}"><button class="btn secondary settings-media-open" type="button">Chọn / thay favicon</button><button id="remove-favicon" class="link-button" type="button" @if(!$favicon) hidden @endif>Bỏ favicon đã chọn</button><small class="hint">Nên dùng ảnh vuông PNG, ICO hoặc WEBP, tối thiểu 32 × 32px.</small></div><div id="preview-favicon" class="seo-image-preview favicon-preview {{ $favicon?'has-image':'' }}">@if($favicon)<img src="{{ $favicon->url }}" alt="Favicon">@else<span>Chưa chọn favicon</span>@endif</div></div></div>
    @foreach(['home'=>'Trang chủ','products'=>'Trang sản phẩm','news'=>'Tin tức & Sự kiện','contact'=>'Liên hệ'] as $key=>$label)
    <div class="panel seo-page-card"><div class="settings-section-head"><div><span class="setting-index">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><h2>{{ $label }}</h2><p>Cấu hình hiển thị trên Google và khi chia sẻ mạng xã hội.</p></div><span class="seo-count" data-seo-count="seo-{{ $key }}">0/180</span></div><div class="settings-grid"><label class="setting-field span-2">Tiêu đề SEO<input id="seo-{{ $key }}" maxlength="180" name="seo[{{ $key }}][title]" value="{{ old("seo.$key.title",$settings["seo.$key.title"]??'') }}" placeholder="{{ $label }} | Thành Đạt Taabusico"></label><label class="setting-field span-2">Mô tả SEO<textarea maxlength="320" rows="3" name="seo[{{ $key }}][description]" placeholder="Mô tả ngắn gọn nội dung trang...">{{ old("seo.$key.description",$settings["seo.$key.description"]??'') }}</textarea></label><label class="setting-field">Ảnh đại diện SEO<select class="seo-image-select" name="seo[{{ $key }}][image_id]" data-preview="preview-{{ $key }}"><option value="" data-url="">Dùng ảnh mặc định</option>@foreach($media as $image)<option value="{{ $image->id }}" data-url="{{ $image->url }}" @selected(old("seo.$key.image_id",$settings["seo.$key.image_id"]??'')==$image->id)>{{ $image->name }}</option>@endforeach</select></label><div id="preview-{{ $key }}" class="seo-image-preview">@php($selected=$media->firstWhere('id',(int)old("seo.$key.image_id",$settings["seo.$key.image_id"]??0)))@if($selected)<img src="{{ $selected->url }}">@else<span>Chưa chọn ảnh</span>@endif</div></div></div>
    @endforeach
</section>
<section class="settings-pane" data-settings-pane="smtp"><div class="panel"><div class="settings-section-head"><div><h2>Máy chủ gửi email</h2><p>Dùng cho email liên hệ, thông báo và khôi phục mật khẩu.</p></div><span class="secure-label">🔒 Mật khẩu được mã hóa</span></div><div class="settings-grid"><label class="setting-field">SMTP Host<input name="smtp[host]" value="{{ old('smtp.host',$settings['smtp.host']??'') }}" placeholder="smtp.gmail.com"></label><label class="setting-field">Cổng<input type="number" name="smtp[port]" value="{{ old('smtp.port',$settings['smtp.port']??587) }}"></label><label class="setting-field">Tài khoản<input name="smtp[username]" value="{{ old('smtp.username',$settings['smtp.username']??'') }}" autocomplete="off"></label><label class="setting-field">Mật khẩu<input type="password" name="smtp[password]" value="" placeholder="{{ filled($settings['smtp.password']??null)?'Đã lưu — để trống nếu không đổi':'Nhập mật khẩu SMTP' }}" autocomplete="new-password"></label><label class="setting-field">Bảo mật<select name="smtp[encryption]"><option value="tls" @selected(($settings['smtp.encryption']??'tls')==='tls')>TLS</option><option value="ssl" @selected(($settings['smtp.encryption']??'')==='ssl')>SSL</option><option value="none" @selected(($settings['smtp.encryption']??'')==='none')>Không mã hóa</option></select></label><label class="setting-field">Email người gửi<input type="email" name="smtp[from_address]" value="{{ old('smtp.from_address',$settings['smtp.from_address']??'') }}" placeholder="hello@example.com"></label><label class="setting-field span-2">Tên người gửi<input name="smtp[from_name]" value="{{ old('smtp.from_name',$settings['smtp.from_name']??'') }}" placeholder="Thành Đạt Taabusico"></label></div></div>
<div class="panel mail-test"><div><h3>Gửi email kiểm tra</h3><p>Hãy lưu cấu hình trước, sau đó nhập email nhận để kiểm tra kết nối.</p></div><a href="#test-mail-form" class="btn secondary">Đi đến kiểm tra mail</a></div></section>
<section class="settings-pane" data-settings-pane="menu"><div class="panel"><div class="settings-section-head"><div><h2>Nội dung menu chính</h2><p>Đổi tên hoặc ẩn/hiện từng mục trên thanh điều hướng.</p></div></div><div class="menu-settings-list">@foreach(['home'=>'Trang chủ','products'=>'Sản phẩm','agriculture'=>'Nông sản','noodles'=>'Phở khô, Bún, Miến, Mì','spices'=>'Gia vị','news'=>'Tin tức & Sự kiện','contact'=>'Liên hệ'] as $key=>$default)<div class="menu-setting-row {{ in_array($key,['agriculture','noodles','spices'])?'submenu':'' }}"><span class="drag-handle">⋮⋮</span><label class="switch"><input type="checkbox" name="menu[{{ $key }}][enabled]" value="1" @checked(old("menu.$key.enabled",($settings["menu.$key.enabled"]??'1'))==='1')><i></i></label><div><b>{{ $default }}</b>@if(in_array($key,['agriculture','noodles','spices']))<small>Mục con của Sản phẩm</small>@endif</div><input name="menu[{{ $key }}][label]" value="{{ old("menu.$key.label",$settings["menu.$key.label"]??$default) }}" placeholder="Tên hiển thị"></div>@endforeach</div></div></section>
<div class="settings-savebar"><span>Thay đổi chỉ áp dụng sau khi lưu.</span><button class="btn">Lưu tất cả cấu hình</button></div></form>
<form id="test-mail-form" class="panel test-mail-form" method="post" action="{{ route('admin.settings.test-mail') }}">@csrf<label class="setting-field">Email nhận thư kiểm tra<input type="email" name="test_email" placeholder="email-cua-ban@example.com" required></label><button class="btn">Gửi email kiểm tra</button></form>
<div id="settings-media-modal" class="media-modal" data-upload-url="{{ route('admin.media.upload') }}" aria-hidden="true"><div class="media-modal-backdrop" data-close-settings-media></div><section class="media-modal-dialog" role="dialog" aria-modal="true" aria-label="Chọn favicon"><header><div><h2>Chọn favicon</h2><p>Chọn ảnh có sẵn hoặc tải ảnh mới lên như thư viện WordPress.</p></div><button type="button" data-close-settings-media aria-label="Đóng">×</button></header><div class="media-tabs"><button class="active" type="button" data-settings-media-tab="library">Thư viện ảnh</button><button type="button" data-settings-media-tab="upload">Tải ảnh mới</button></div><div class="media-tab-pane active" data-settings-media-pane="library"><div id="settings-media-grid" class="modal-media-grid">@foreach($media as $image)<button type="button" class="modal-media-item settings-media-item {{ $favicon?->id===$image->id?'selected':'' }}" data-media-id="{{ $image->id }}" data-media-url="{{ $image->url }}" data-media-name="{{ $image->name }}"><img src="{{ $image->url }}" alt="{{ $image->alt_text }}" loading="lazy"><span>{{ $image->name }}</span></button>@endforeach</div></div><div class="media-tab-pane" data-settings-media-pane="upload"><div class="wp-upload-box"><span><i class="fa-regular fa-image"></i></span><h3>Thả ảnh vào đây để tải lên</h3><p>hoặc</p><label class="btn">Chọn ảnh từ máy tính<input id="settings-media-upload" type="file" accept="image/*,.ico" hidden></label><small>PNG, ICO, WEBP hoặc JPG · Tối đa 5MB</small><div id="settings-media-progress" class="upload-progress" hidden><i></i><span>Đang tải ảnh...</span></div></div></div><footer><div id="settings-selected-media-name">{{ $favicon?->name?:'Chưa chọn ảnh' }}</div><button class="btn" id="confirm-settings-media" type="button" @if(!$favicon) disabled @endif>Dùng làm favicon</button></footer></section></div>
@endsection
