@extends('layouts.admin')
@section('title',$banner->exists?'Sửa banner':'Thêm banner')
@section('content')
@php($selected=$media->firstWhere('id',(int)old('image_id',$banner->image_id)))
<div class="admin-title"><div><h1>{{ $banner->exists?'Sửa banner':'Thêm banner' }}</h1><p>Ảnh phủ toàn bộ banner, nội dung nằm bên trái.</p></div><a class="admin-back-btn" href="{{ route('admin.banners.index') }}"><i class="fa-solid fa-arrow-left"></i> Quay lại</a></div>
@if($errors->any())<div class="alert error">{{ $errors->first() }}</div>@endif
<form class="editor banner-editor" method="post" action="{{ $banner->exists?route('admin.banners.update',$banner):route('admin.banners.store') }}">
    @csrf @if($banner->exists)@method('put')@endif
    <div><section class="panel form-grid"><label>Vị trí banner<select name="placement"><option value="home" @selected(old('placement',$banner->placement?:'home')==='home')>Trang chủ</option><option value="about" @selected(old('placement',$banner->placement)==='about')>Trang giới thiệu</option></select></label><label>Kiểu hiển thị<select name="display_mode" data-banner-display-mode><option value="with_text" @selected(old('display_mode',$banner->display_mode?:'with_text')==='with_text')>Ảnh và nội dung chữ</option><option value="image_only" @selected(old('display_mode',$banner->display_mode)==='image_only')>Chỉ hiển thị ảnh</option></select></label><div class="span-2 form-grid banner-text-fields" data-banner-text-fields><label>Nhãn nhỏ<input name="eyebrow" value="{{ old('eyebrow',$banner->eyebrow) }}"></label><label>Tiêu đề chính<input name="title" value="{{ old('title',$banner->title) }}"></label><label class="span-2">Tiêu đề phụ<input name="subtitle" value="{{ old('subtitle',$banner->subtitle) }}"></label><label class="span-2">Mô tả<textarea name="description" rows="3">{{ old('description',$banner->description) }}</textarea></label><label>Nhãn nút<input name="button_label" value="{{ old('button_label',$banner->button_label?:'Khám phá ngay') }}"></label><label>Liên kết nút<input name="button_url" value="{{ old('button_url',$banner->button_url?:route('products.index')) }}"></label><label>Màu chữ<select name="text_color"><option value="dark" @selected(old('text_color',$banner->text_color?:'dark')==='dark')>Chữ tối</option><option value="light" @selected(old('text_color',$banner->text_color)==='light')>Chữ sáng</option></select></label></div><label>Thứ tự<input type="number" min="0" name="sort_order" value="{{ old('sort_order',$banner->sort_order??0) }}"></label></section></div>
    <aside>
        <section class="panel banner-media-panel"><h3>Ảnh banner</h3><input id="featured-image-id" type="hidden" name="image_id" value="{{ old('image_id',$banner->image_id) }}"><div id="featured-preview" class="banner-image-preview featured-preview {{ $selected?'has-image':'' }}">@if($selected)<img src="{{ $selected->url }}" alt="{{ $selected->alt_text }}">@else<span>Chưa chọn ảnh banner</span>@endif</div><button class="media-modal-open btn secondary" type="button">Chọn / thay ảnh banner</button><button id="remove-featured" class="link-button" type="button" @if(!$selected) hidden @endif>Bỏ ảnh đã chọn</button><p class="hint">Khuyến nghị 1920 × 600px, vùng bên trái đủ thoáng để đặt chữ.</p></section>
        <section class="panel"><label class="check"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$banner->exists?$banner->is_active:true))> Hiển thị banner</label></section><button class="btn banner-save">Lưu banner</button>
    </aside>
</form>

<div id="media-modal" class="media-modal" data-upload-url="{{ route('admin.media.upload') }}" aria-hidden="true">
    <div class="media-modal-backdrop" data-close-media></div><section class="media-modal-dialog" role="dialog" aria-modal="true" aria-label="Chọn ảnh banner">
        <header><div><h2>Chọn ảnh banner</h2><p>Tải ảnh mới hoặc chọn ảnh đã có trong thư viện.</p></div><button type="button" data-close-media aria-label="Đóng">×</button></header>
        <div class="media-tabs"><button class="active" type="button" data-media-tab="library">Thư viện ảnh</button><button type="button" data-media-tab="upload">Tải ảnh mới</button></div>
        <div class="media-tab-pane active" data-media-pane="library"><div id="modal-media-grid" class="modal-media-grid">@foreach($media as $image)<button type="button" class="modal-media-item {{ old('image_id',$banner->image_id)==$image->id?'selected':'' }}" data-media-id="{{ $image->id }}" data-media-url="{{ $image->url }}" data-media-name="{{ $image->name }}"><img src="{{ $image->url }}" alt="{{ $image->alt_text }}" loading="lazy"><span>{{ $image->name }}</span></button>@endforeach</div></div>
        <div class="media-tab-pane" data-media-pane="upload"><div class="wp-upload-box"><span><i class="fa-regular fa-image"></i></span><h3>Thả ảnh vào đây để tải lên</h3><p>hoặc</p><label class="btn">Chọn ảnh từ máy tính<input id="featured-upload" type="file" accept="image/*" hidden></label><small>JPG, PNG, WEBP · Tối đa 5MB</small><div id="upload-progress" class="upload-progress" hidden><i></i><span>Đang tải ảnh...</span></div></div></div>
        <footer><div id="selected-media-name">{{ $selected?->name?:'Chưa chọn ảnh' }}</div><button class="btn" id="confirm-featured" type="button" @if(!$selected) disabled @endif>Dùng làm ảnh banner</button></footer>
    </section>
</div>
@endsection
