@php
    $pageKey=request()->routeIs('products.*')?'products':(request()->routeIs('news.*')?'news':(request()->routeIs('about')?'about':(request()->routeIs('contact')?'contact':'home')));
    $defaultTitle=trim($__env->yieldContent('title'))?:($siteSettings['site.name']??'Nông Sản Việt');
    $seoTitle=filled($siteSettings["seo.$pageKey.title"]??null)?$siteSettings["seo.$pageKey.title"]:$defaultTitle;
    $seoDescription=filled($siteSettings["seo.$pageKey.description"]??null)?$siteSettings["seo.$pageKey.description"]:'Nông sản Việt Nam chất lượng, nguồn gốc rõ ràng.';
    $seoImage=filled($siteSettings["seo.$pageKey.image_url"]??null)?$siteSettings["seo.$pageKey.image_url"]:asset('images/brand/thanhdat-logo.png');
    if(isset($post)&&request()->routeIs('news.show')){$seoTitle=$post->title;$seoDescription=$post->excerpt?:$seoDescription;$seoImage=$post->featuredImage?->url?:$seoImage;}
    if(isset($product)&&request()->routeIs('products.show')){$seoTitle=$product->name;$seoDescription=$product->short_description?:$seoDescription;$seoImage=$product->primary_image?->url?:$seoImage;}
    $menuEnabled=fn($key)=>($siteSettings["menu.$key.enabled"]??'1')==='1';
    $menuLabel=fn($key,$default)=>filled($siteSettings["menu.$key.label"]??null)?$siteSettings["menu.$key.label"]:$default;
@endphp
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">@if(filled($siteSettings['site.favicon_url']??null))<link rel="icon" href="{{ $siteSettings['site.favicon_url'] }}">@endif<meta name="description" content="{{ $seoDescription }}"><meta property="og:locale" content="vi_VN"><meta property="og:type" content="{{ request()->routeIs('news.show')?'article':'website' }}"><meta property="og:title" content="{{ $seoTitle }}"><meta property="og:description" content="{{ $seoDescription }}"><meta property="og:image" content="{{ $seoImage }}"><meta property="og:url" content="{{ url()->current() }}"><meta name="twitter:card" content="summary_large_image"><title>{{ $seoTitle }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head><body>
<header class="store-header"><div class="store-top"><div class="container"><div><span><i class="fa-solid fa-headset"></i> Hỗ trợ khách hàng: <b>0938.905.582</b></span><span><i class="fa-regular fa-envelope"></i> Email: congtytdfoods@gmail.com</span></div><div><a href="{{ route('about') }}">Về chúng tôi</a><a href="{{ route('news.index') }}">Tin tức</a><a href="{{ route('policy') }}">Chính sách</a></div></div></div>
<div class="store-main container"><a class="store-logo" href="{{ route('home') }}"><img src="{{ asset('images/brand/thanhdat-logo.png') }}" alt="Thành Đạt Taabusico"></a><form class="store-search" action="{{ route('products.index') }}"><input name="q" value="{{ request('q') }}" placeholder="Tìm kiếm nông sản, đặc sản, sản phẩm..."><button aria-label="Tìm kiếm"><i class="fa-solid fa-magnifying-glass"></i></button></form><div class="store-perks"><div><i class="fa-solid fa-truck-fast"></i><span><b>Giao hàng</b><small>toàn quốc</small></span></div><div><i class="fa-solid fa-money-bill-wave"></i><span><b>Thanh toán</b><small>khi nhận hàng</small></span></div><a href="{{ route('products.index') }}"><i class="fa-solid fa-cart-shopping"></i><span><b>Giỏ hàng</b><small>Khám phá ngay</small></span></a></div></div>
<nav class="store-nav"><div class="container"><a class="category-menu" href="{{ route('products.index') }}"><span><i class="fa-solid fa-bars"></i></span> DANH MỤC SẢN PHẨM</a><button class="menu-toggle" aria-label="Mở menu" aria-expanded="false"><i class="fa-solid fa-bars"></i></button><div class="nav-links">@if($menuEnabled('home'))<a class="{{ request()->routeIs('home')?'active':'' }}" href="{{ route('home') }}">{{ $menuLabel('home','Trang chủ') }}</a>@endif<a class="{{ request()->routeIs('about')?'active':'' }}" href="{{ route('about') }}">Giới thiệu</a>@if($menuEnabled('products'))<a class="{{ request()->routeIs('products.*')?'active':'' }}" href="{{ route('products.index') }}">{{ $menuLabel('products','Sản phẩm') }}</a>@endif @if($menuEnabled('news'))<a class="{{ request()->routeIs('news.*')?'active':'' }}" href="{{ route('news.index') }}">{{ $menuLabel('news','Tin tức') }}</a>@endif @if($menuEnabled('contact'))<a class="{{ request()->routeIs('contact')?'active':'' }}" href="{{ route('contact') }}">{{ $menuLabel('contact','Liên hệ') }}</a>@endif</div></div></nav></header>
<main>@yield('content')</main><section class="store-assurances"><div class="container"><div><i class="fa-solid fa-award"></i><span><b>Cam kết chất lượng</b><small>Nông sản sạch 100%</small></span></div><div><i class="fa-solid fa-headset"></i><span><b>Hỗ trợ 24/7</b><small>Tư vấn nhiệt tình</small></span></div><div><i class="fa-solid fa-truck-fast"></i><span><b>Giao hàng nhanh</b><small>Phạm vi toàn quốc</small></span></div><div><i class="fa-regular fa-credit-card"></i><span><b>Thanh toán linh hoạt</b><small>Nhiều hình thức</small></span></div><a href="tel:0938905582" style="justify-self:center;align-self:center;display:flex;align-items:center;justify-content:center;padding:12px 18px;white-space:nowrap"><i class="fa-solid fa-phone"></i> 0938.905.582</a></div></section>
<footer><div class="container footer-grid"><div><a class="footer-logo" href="{{ route('home') }}"><img src="{{ asset('images/brand/thanhdat-logo.png') }}" alt="Thành Đạt Taabusico"></a><p>CÔNG TY TNHH THỰC PHẨM SẠCH THÀNH ĐẠT TD FOODS</p></div><div><h4>Khám phá</h4><a href="{{ route('products.index') }}">Tất cả sản phẩm</a><a href="{{ route('about') }}">Về chúng tôi</a><a href="{{ route('news.index') }}">Tin tức & sự kiện</a></div><div><h4>Liên hệ</h4><p>NS 30, Ngõ 50, Tổ 6 Mễ Trì Thượng, Quận Nam Từ Liêm, HN</p><p><a href="mailto:congtytdfoods@gmail.com">congtytdfoods@gmail.com</a></p><p><a href="tel:0938905582">0938.905.582</a></p><p>Facebook: nongsansach</p></div></div><div class="copyright">© {{ date('Y') }} CÔNG TY TNHH THỰC PHẨM SẠCH THÀNH ĐẠT TD FOODS. Tự hào nông sản Việt Nam.</div></footer></body></html>
