@extends('layouts.app')
@section('title', 'Đặt mua '.$product->name)
@section('content')
<section class="page-hero compact"><div class="container"><span class="eyebrow">Đặt hàng trực tuyến</span><h1>Thông tin giao hàng</h1><p>Điền thông tin chính xác để Thành Đạt giao hàng đến bạn.</p></div></section>
<form class="checkout-layout container" method="post" action="{{ route('orders.store', $product->slug) }}">@csrf
    <section class="checkout-form panel"><h2>Thông tin người nhận</h2><div class="checkout-fields"><label>Họ và tên *<input name="customer_name" value="{{ old('customer_name') }}" required>@error('customer_name')<small class="field-error">{{ $message }}</small>@enderror</label><label>Số điện thoại *<input name="phone" value="{{ old('phone') }}" placeholder="09xxxxxxxx" required>@error('phone')<small class="field-error">{{ $message }}</small>@enderror</label><label>Email<input type="email" name="email" value="{{ old('email') }}" placeholder="Không bắt buộc">@error('email')<small class="field-error">{{ $message }}</small>@enderror</label><label>Số lượng *<input id="order-quantity" type="number" name="quantity" min="1" max="{{ $product->stock }}" value="{{ old('quantity', 1) }}" data-price="{{ (int) $product->price }}" required>@error('quantity')<small class="field-error">{{ $message }}</small>@enderror</label><label class="span-2">Địa chỉ nhận hàng *<textarea name="address" rows="3" placeholder="Số nhà, đường, phường/xã, quận/huyện, tỉnh/thành" required>{{ old('address') }}</textarea>@error('address')<small class="field-error">{{ $message }}</small>@enderror</label><label class="span-2">Ghi chú<textarea name="note" rows="2" placeholder="Thời gian nhận hàng hoặc yêu cầu khác">{{ old('note') }}</textarea></label></div>
    <h2>Phương thức thanh toán</h2><div class="payment-options"><label><input type="radio" name="payment_method" value="cod" @checked(old('payment_method', 'cod') === 'cod')><span><b><i class="fa-solid fa-money-bill-wave" aria-hidden="true"></i> Thanh toán khi nhận hàng</b><small>Thanh toán tiền mặt cho nhân viên giao hàng.</small></span></label><label><input type="radio" name="payment_method" value="payos" @checked(old('payment_method') === 'payos')><span><b><i class="fa-solid fa-building-columns" aria-hidden="true"></i> Chuyển khoản qua PayOS</b><small>Quét mã QR hoặc thanh toán ngân hàng an toàn.</small></span></label></div>@error('payment_method')<small class="field-error">{{ $message }}</small>@enderror</section>
    <aside class="checkout-summary panel"><h2>Đơn hàng của bạn</h2><div class="checkout-product">@if($product->primary_image)<img src="{{ $product->primary_image->url }}" alt="{{ $product->name }}">@endif<div><b>{{ $product->name }}</b><small>{{ number_format($product->price,0,',','.') }}đ / {{ $product->unit }}</small></div></div><div class="checkout-total"><span>Tạm tính</span><b id="order-subtotal">{{ number_format($product->price,0,',','.') }}đ</b></div><div class="checkout-total"><span>Phí vận chuyển</span><b>Miễn phí</b></div><div class="checkout-grand-total"><span>Tổng thanh toán</span><strong id="order-total">{{ number_format($product->price,0,',','.') }}đ</strong></div><button class="btn checkout-submit">Đặt hàng ngay</button><small class="checkout-policy">Bằng việc đặt hàng, bạn đồng ý để cửa hàng sử dụng thông tin trên cho mục đích xử lý và giao đơn hàng.</small></aside>
</form>
@endsection
